In [1]:
from env import Env
from player import Player
import numpy
import pandas

Using TensorFlow backend.


In [2]:
df = pandas.read_csv("dataset/feature.csv")
train_df = df[10000:20000].reset_index(drop=True)
test_df = df[20000:].reset_index(drop=True)

In [3]:
train_env = Env(train_df)
test_env = Env(test_df)


In [4]:
action_size, csv_size, img_size = train_env.action_size, train_env.csv_size, train_env.img_size

In [5]:
player = Player(action_size, csv_size, img_size)

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
player.actor.load_weights("model/actor_weight.h5")
player.critic.load_weights("model/critic_weight.h5")

In [7]:
test_env.reset()

test_env.capability = 1
obs1 = test_env.observation(test_df, 1000)
csv1, img1 = obs1

test_env.capability = 2
obs2 = test_env.observation(test_df, 1000)
csv2, img2 = obs2

In [8]:
player.actor.predict([csv1, img1])

array([[0., 1., 0.]], dtype=float32)

In [9]:
player.actor.predict([csv2, img2])

array([[0., 1., 0.]], dtype=float32)

In [10]:
player.get_action_prob(obs2)

array([0., 1., 0.], dtype=float32)

In [19]:
cap = 0.9 + numpy.array(range(100)) * 0.01
action_list = []
for c in cap:
    test_env.capability = c
    obs = test_env.observation(test_df, 1000)
    csv, img = obs
    action = player.actor.predict([csv, img])[0][0]
    action_list.append(action)

In [20]:
action_list

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]